version: "3.3"
services:
  cockroachdb:
    image: "cockroachdb/cockroach-unstable:v22.1.0-alpha.5"
    command: "start-single-node --insecure"
  psycopg2:
    image: "python:3.8-buster"
    command: "/code/build_test_psycopg2.sh"
    volumes:
      - .:/code
